/*
 * commands_def.h
 *
 *  Created on: May 20, 2020
 *      Author: mx
 */

#ifndef COMMANDS_DEF_H_
#define COMMANDS_DEF_H_

enum SYSTEMS
{
	IO_SYSTEM = 1,
	NGC_SYSTEM = 2,
	TASK_SYSTEM = 3
};



enum IO_cmd
{
	SET_SIM = 0,
	SET_ACT = 1,
	SET_DIGITAL = 2,
	SET_ANALOG = 3,
	AUTO_START = 4,
	AUTO_STOP = 5
};



enum NGC_cmd
{
	SET_FU_REF = 0,
	SET_FV_REF = 1,
	SET_FW_REF = 2,
	SET_TR_REF = 3,

	SET_U_REF = 4,
	SET_V_REF = 5,
	SET_W_REF = 6,
	SET_R_REF = 7,

	SET_SPEED_REF = 8,
	SET_COURSE_REF = 9,

	SET_X_REF = 10,
	SET_Y_REF = 11,
	SET_Z_REF = 12,
	SET_ALT_REF = 13,
	SET_PSI_REF = 14,
};


enum Task_cmd
{
	SET_ANG_SENSOR = 4,
	SET_HOR_VEL_SENSOR = 5,
	SET_HOR_POS_SENSOR = 6,
	SET_VER_VEL_SENSOR = 7,
	SET_VER_POS_SENSOR = 8,
	SET_ALT_SENSOR = 9,

	SET_ANG_RAW_FILTER = 10,
	SET_HOR_VEL_RAW_FILTER = 11,
	SET_HOR_POS_RAW_FILTER = 12,
	SET_VER_VEL_RAW_FILTER = 13,
	SET_VER_POS_RAW_FILTER = 14,
	SET_ALT_RAW_FILTER = 15,

	INIT_ANG_FILTER = 16,
	INIT_HOR_VEL_FILTER = 17,
	INIT_HOR_POS_FILTER = 18,
	INIT_VER_VEL_FILTER = 19,
	INIT_VER_POS_FILTER = 20,
	INIT_ALT_FILTER = 21,

	ANG_VEL_CONTROL = 26,
	ANG_POS_CONTROL = 27,
	HOR_VEL_CONTROL = 28,
	HOR_POS_CONTROL = 29,
	VER_VEL_CONTROL = 30,
	VER_POS_CONTROL = 31,
	ALT_CONTROL = 32,

	SET_TASK_PARAM = 33,
	GET_TASK_PARAMS = 34,

	PATH_FOLLOWING_FA_CONTROL = 35,
	PATH_FOLLOWING_UA_CONTROL = 36,

	THRUST_MAPPING = 37,
};



enum Path_cmd
{
	PATH_PLANNER_ACTIVATE = 0,
	PATH_PLANNER_COMPUTE_LINE = 1,
	PATH_PLANNER_COMPUTE_CIRCLE = 2,
	PATH_PLANNER_COMPUTE_SPLINE = 3,
};


#endif /* COMMANDS_DEF_H_ */
